/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package httpserver.app;

import java.io.IOException;
import java.net.ServerSocket;

public class App {

    public void listener(int port) {
        try (ServerSocket server = new ServerSocket(port)) {

            // Enter an infinite loop, waiting for clients to connect
            while (true) {

                /*
                 * Handle the request in a separate thread so we don't block
                 * the main thread
                 */
                HTTPWorker worker = new HTTPWorker(server.accept());
                Thread t = new Thread(worker);
                t.start();
            }
        }

        catch (IOException ex) {
            System.out.println("IO Exception: " + ex.getMessage());
        }

    }

    public static void main(String[] args) {

        // Default port
        int port = 8080;

        // Accept alternative port as argument
        if (args.length > 0) {
            try {
                port = Integer.parseInt(args[0]);
            }

            catch (IllegalArgumentException ex) {
                System.out.println("Invalid port, using default");
            }
        }

        // Start listening for connections
        new App().listener(port);
    }
}
